### PR TITLE
Square bracket support closes #42

### LINKED ISSUE #42: link text can't contains `]`
### Describe the bug

`[[test]](test.md)` and `[\[test\]](test.md)` won't be processed.

### Expected behavior

All valid markdown links should be processed.

### Additional context

It seems we should adjust the [regex in the source code](https://github.com/benbalter/jekyll-relative-links/blob/5e90d5307b54969079fe745d12ceb715bc4b8527/lib/jekyll-relative-links/generator.rb#L10) to fix it.

### PR DESCRIPTION
**Pull request by andymond**
* Change LINK_TEXT_REGEX constant to %r!(.*?)! in generator.rb
* Add nested bracket & escaped nested bracket links to page.md fixture
* Add tests for nested bracket link & escaped nested bracket link to generator_spec.rb
* All tests and builds in script/cibuild passing

### CODE REVIEW

File: lib/jekyll-relative-links/generator.rb [hunk 1]
```diff
@@ -7,7 +7,7 @@ class Generator < Jekyll::Generator
     # Use Jekyll's native relative_url filter
     include Jekyll::Filters::URLFilters
 
-    LINK_TEXT_REGEX = %r!([^\]]+)!
+    LINK_TEXT_REGEX = %r!([^\]]+|.*)!
```
Comment (benbalter) [inline lib/jekyll-relative-links/generator.rb]: If I'm reading this correctly, this is "any character other than `]` OR any character". Is there an advantage to that over just `.*`  or `.*?`? It looks like this still allows us to support multiple links on the same line?
